repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: '' # Use the sha / tag you want to point at
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@2.5.1
          - 'prettier-plugin-tailwindcss'
